### ISSUE TITLE
[文档]: 详细文档已经无法打开了

### ISSUE THREAD

**Issue by ZeroMah** [catlair/BiliTools#116]
### 问题描述

https://btdocs.vercel.app/

**Comment by KudouRan** [comment]
vercel 似乎因为不可抗力无法访问了，使用梯子可以。

文档其实还有个 https://catlair.github.io/BiliTools/ 但也是时常无法访问。目前没有什么解决办法

**Comment by ZeroMah** [comment]
感谢，可以浏览
