### ISSUE TITLE
类似项目出现action被禁止

### ISSUE THREAD

**Issue by catlair** [catlair/BiliTools#14]
个人比较推荐使用云函数运行。

**Comment by KudouRan** [comment]
选择	`Nodejs12.16`环境，运行时竟然是这样的
![image](https://user-images.githubusercontent.com/81743795/116541034-82e31d00-a91d-11eb-930a-5b8abe2cba98.png)

**Comment by catlair** [comment]
`serverless.yaml`可以用环境变量配置，或者直接使用`tencentcloud-sdk-nodejs`

**Comment by catlair** [comment]
#16
