### ISSUE TITLE
【文档】手动部署项目到腾讯云函数（scf）

### ISSUE THREAD

**Issue by catlair** [catlair/BiliTools#18]
doing...

**Comment by catlair** [comment]
## 下载最新版的 [tencent_scf.zip 压缩包](https://github.com/catlair/BiliTools/releases) 
![image](https://user-images.githubusercontent.com/44313800/119252421-bd6b6d00-bbde-11eb-9d79-bf788593af9c.png)

**Comment by catlair** [comment]
## 2. 新增 scf 

[点击进入云函数控制台](https://console.cloud.tencent.com/scf)

![Snipaste_2021-05-23_14-37-50](https://user-images.githubusercontent.com/44313800/119252529-6ca84400-bbdf-11eb-98e2-5bd87f3717ff.png)

填写基本的信息
- 运行环境选择最新的 `Nodejs`

![Snipaste_2021-05-23_14-41-45](https://user-images.githubusercontent.com/44313800/119252549-8b0e3f80-bbdf-11eb-9ea1-efb14cbd5f2c.png)

选择上传刚才下载的压缩包

![Snipaste_2021-05-23_14-42-46](https://user-images.githubusercontent.com/44313800/119252577-b133df80-bbdf-11eb-993c-ffcf893800fc.png)

更多高级配置

![image](https://user-images.githubusercontent.com/44313800/119252605-cd378100-bbdf-11eb-85a6-ca6aa97ea445.png)
![image](https://user-images.githubusercontent.com/44313800/119252627-e4766e80-bbdf-11eb-9c53-359877711c20.png)

**Comment by catlair** [comment]
## 3. 新建配置文件并测试是否可用

https://user-images.githubusercontent.com/44313800/119252722-4cc55000-bbe0-11eb-8910-4d63599d4f9b.mp4

配置文件（`config.json`）的示例，
![image](https://user-images.githubusercontent.com/44313800/119252921-50a5a200-bbe1-11eb-9116-48986c345759.png)


```json
{
  "function": {
    "silver2Coin": false,
    "liveSignTask": false,
    "addCoins": false,
    "mangaSign": false,
    "shareAndWatch": false,
    "supGroupSign": false,
    "judgement": true,
    "liveSendMessage": false
  },
  "dailyRunTime": "19:19:19-23:23:23",
  "apiDelay": [20, 50],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
  "cookie": "哈哈哈哈",
  "message": true,
  "stayCoins": 0,
  "targetCoins": 5,
  "targetLevel": 6,
  "coinRetryNum": 6,
  "upperAccMatch": true,
  "customizeUp": [],
  "sls": {
    "name": "bilitool_scf_demo",
    "region": "ap-chengdu"
  }
}

```
注：
- `sls` 字段是实现随机运行需要的内容（函数名和函数地域）
- `json` 不支持注释

**Comment by catlair** [comment]
## 4. 增加触发器

![Snipaste_2021-05-23_15-42-09](https://user-images.githubusercontent.com/44313800/119252987-a11cff80-bbe1-11eb-8f3f-f4791f3d7ea4.png)

若要使用随机执行须注意
- 每日任务的触发器名为`daily_bili_timer`
- 风纪任务的触发器名为`jury_bili_timer`

![Snipaste_2021-05-23_15-45-35](https://user-images.githubusercontent.com/44313800/119252991-a5e1b380-bbe1-11eb-92e7-62ab431ca392.png)

![Snipaste_2021-05-23_15-47-19](https://user-images.githubusercontent.com/44313800/119252996-a9753a80-bbe1-11eb-93ea-f7bceba34f44.png)

**Comment by Google-Skillshop** [comment]
> ## 3. 新建配置文件并测试是否可用
>  bandicam.2021-05-23.15-38-19-710.mp4 
> 配置文件（`config.json`）的示例，
> ![image](https://user-images.githubusercontent.com/44313800/119252921-50a5a200-bbe1-11eb-9116-48986c345759.png)
> 
> ```json
> {
>   "function": {
>     "silver2Coin": false,
>     "liveSignTask": false,
>     "addCoins": false,
>     "mangaSign": false,
>     "shareAndWatch": false,
>     "supGroupSign": false,
>     "judgement": true,
>     "liveSendMessage": false
>   },
>   "dailyRunTime": "19:19:19-23:23:23",
>   "apiDelay": [20, 50],
>   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
>   "cookie": "哈哈哈哈",
>   "message": true,
>   "stayCoins": 0,
>   "targetCoins": 5,
>   "targetLevel": 6,
>   "coinRetryNum": 6,
>   "upperAccMatch": true,
>   "customizeUp": [],
>   "sls": {
>     "name": "bilitool_scf_demo",
>     "region": "ap-chengdu"
>   }
> }
> ```
> 
> 注：
> 
> * `sls` 字段是实现随机运行需要的内容（函数名和函数地域）
> * `json` 不支持注释

## 这里 `Bilibili Cookie` 格式是什么呢？
