### ISSUE TITLE
【文档】Action 自动部署项目到腾讯云函数（scf）

### ISSUE THREAD

**Issue by catlair** [catlair/BiliTools#20]
## 获取 SCF 的授权ID/KEY

获取 key 参考[腾讯云权限管理](https://console.cloud.tencent.com/cam/capi)

**Comment by catlair** [comment]
## 1. 基本配置

填写表单就能够获取配置了`[初步测试版]`<https://catlair.gitee.io/bili-tools-docs-deploy/>

为了避免配置中的特殊符号影响，配置必须进行压缩(压缩也可以减少配置的大小)，下面是压缩地址(参考百度 Helper 进行的压缩)  
json 数据在线压缩地址<https://catlair.gitee.io/bili-tools-docs-deploy/#/data/format>

`api`的调用速度配置对部分情况不会生效，该部分使用了个人觉得应该使用的最小区间，就不做更大范围的兼容了

[仓库地址](https://github.com/catlair/BiliTools-docs)

**Comment by catlair** [comment]
## 2. Github secrets

- fork 本仓库
- 按照下图配置 ID/KEY/Config

![setting](https://user-images.githubusercontent.com/44313800/119254819-25c04b80-bbeb-11eb-9aec-67977eb7ddba.png)

![setting-new](https://user-images.githubusercontent.com/44313800/119254821-2822a580-bbeb-11eb-8b41-fd5bbac584fc.png)

![setting-new-2](https://user-images.githubusercontent.com/44313800/119254825-29ec6900-bbeb-11eb-9bea-22b08d402916.png)

**Comment by catlair** [comment]
## 3. 手动运行 Action

![image](https://user-images.githubusercontent.com/44313800/119254912-83ed2e80-bbeb-11eb-9321-b4c88ffd66fe.png)

**Comment by KudouRan** [comment]
由于某个问题，不提供自动更新 fork 的方法，如需下图方法手动更新

![图片](https://user-images.githubusercontent.com/81743795/125163899-e3b28f80-e1c1-11eb-89fb-afed60e278dc.png)
