### ISSUE TITLE
【文档】通过浏览器获取 cookies

### ISSUE THREAD

**Issue by catlair** [catlair/BiliTools#23]
以 PC 端浏览器（Firefox）举例（推荐使用 Firefox/Chrome/Chromium Edge）

最终 Cookie 是这样的（为了演示方便换了行，实际只有一行）

```text
_uuid=D2282D0F-257B-845A-BDF5-C770ED288F4001440infoc; buvid3=BF17608E-FB87-4F49-A922-56FD2E284D6F18534infoc; 
fingerprint=5502cd4fe9637738de04bd9c3d1bdbc5; 
buvid_fp=BF17608E-FB87-4F49-A922-56FD2E284D6F18534infoc; 
SESSDATA=21607773%2C1631089673%2C71a42%2A31; bili_jct=dd92c55a6d67041ce2f3fb1650889ea8; 
DedeUserID=521268093; DedeUserID__ckMd5=47d541f04b605da9; 
sid=ivie73r8; fingerprint3=792b32adfecbe31a4aca53ab7be1ad76; 
fingerprint_s=bb6736758e7344a295c2ed6070cc642e; 
buvid_fp_plain=BF17608E-FB87-4F49-A922-56FD2E284D6F18534infoc; 
CURRENT_FNVAL=80; blackside_state=1; rpdid=|(kmJYYJ)lkR0J'uYu)llkJYJ; _dfcaptcha=a46d7562a42065d43a88c053e283e876; 
LIVE_BUVID=AUTO8016188357987702; bsource=search_baidu; PVID=2
```

**Comment by KudouRan** [comment]
## Firefox

任意方式进入 b 站（搜索，收藏夹，地址访问等） 
按 F12 （或者右键 --> 检查）打开开发者工具，切换到`网络` ( `network` )  
点击重新载入（或者按 F5，Ctrl + R 等）刷新页面

![图片](https://user-images.githubusercontent.com/81743795/125189079-0946a400-e269-11eb-9566-2f5c5a1e62fc.png)

点击某一个请求（通常为 `nav` ） 

![图片](https://user-images.githubusercontent.com/81743795/125189280-e4066580-e269-11eb-80dd-9d7cc6a27473.png)

**Comment by KudouRan** [comment]
## Chrome/Chromium

任意方式进入 b 站（搜索，收藏夹，地址访问等）  
按 F12 （或者右键 --> 检查）打开开发者工具，切换到 `网络` ( `network` )  
点击重新载入（或者按 F5，Ctrl + R 等）刷新页面   
点击某一个请求（通常为 nav ）  

![图片](https://user-images.githubusercontent.com/81743795/125189400-7d357c00-e26a-11eb-9e6f-00b3630de0df.png)
