### ISSUE TITLE
建议增加一个云函数内存的变量

### ISSUE THREAD

**Issue by ttt789-ppo** [catlair/BiliTools#34]
我是通过action推送到云函数的，但是没有内存的变量，默认64m每次还没运行完占了64m后就错误了，希望增加一个变量可以选择128m，手动改的话会被action推送过去的覆盖就没了

**Comment by catlair** [comment]
现在已经增加到 128 了
[其他大小配置详见]https://github.com/catlair/BiliTools/blob/main/docs/configuration.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

没写在文档中的：在`config/config.json` 中添加 memorySize 字段（所有用户），在每个用户的配置中添加 memorySize  字段（单个用户）。
