### ISSUE TITLE
请问如何本地（Windows）运行 啊

### ISSUE THREAD

**Issue by davidelectricfree** [catlair/BiliTools#40]
手上有一台Windows的服务器，因此想将项目部署在服务器上，这个项目如何本地运行呢？读完所有的README都是DOCKER和云函数

**Comment by catlair** [comment]
没有想过有人会用且在本地用😓

**Comment by KudouRan** [comment]
https://github.com/catlair/BiliTools/blob/main/docs/%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C.md#%E5%8D%95%E7%94%A8%E6%88%B7
