### ISSUE TITLE
大佬可以增加 arm64 的 docker 么？

### ISSUE THREAD

**Issue by laincat** [catlair/BiliTools#41]

**Comment by catlair** [comment]
我也不懂这个，用 buildx 添加了，不知道是否可行  
![image](https://user-images.githubusercontent.com/44313800/139567436-5c33215a-4701-416d-879b-3b3be1a64894.png)

**Comment by laincat** [comment]
看起来是运作了.

在研究怎么设置，看不明白怎么设置。。。。
