### ISSUE TITLE
大佬，经常遇到 登录失败。另外可以加一个 Bark 的推送嘛？

### ISSUE THREAD

**Issue by laincat** [catlair/BiliTools#42]
提示：

`[08:57:59]  登录失败:  Error: Client network socket disconnected before secure TLS connection was established`

**Comment by KudouRan** [comment]
1.  我无法复现这个错误，不知道是网络原因还是请求头出现错误（可以检查一下 UA 等配置）。对于请求异常，我增加了至少 2 次重试请求。  
2. 这个脚本我早就没用了（除了挂了小号检测一下基本的使用，大多数问题都无法发现），不想花时间去做太多更新。对于推送，我增加了一个自定义 api （只支持 get 请求）用法如下：

在 配置 文件的 `message` 中增加 `api `；

```json
  "message": {
    "email": {
      "from": "dinglei@163.com",
      "to": "mahuateng@qq.com",
      "pass": "JKLASDGAHJSGDHJAF",
      "host": "smtp.163.com",
      "port": 465
    },
    "api": "https://sed.demo.com/send?title={title}&text={text}"
  },
```

其中 `{title}` 和 `{text}` 是占位符号，放在用于接收标题和内容的位置  
再举个例子 `https://api.day.app/yourkey/{title}/{text}`

**Comment by laincat** [comment]
好的，深表感谢。

**Comment by catlair** [comment]
推送已经支持了
