### ISSUE TITLE
是否可以出一个支持青龙的版本

### ISSUE THREAD

**Issue by 17huiwei** [catlair/BiliTools#44]
应该是比较主流的支持。

当然，docker也是一种很不错的方式。

**Comment by catlair** [comment]
没了解过什么是青龙

**Comment by lsdlh** [comment]
> 没明白过什么是青龙
> 
> 只看如何安装，没看到使用文档

就是一个面板，能定时运行一些任务脚本，比如js、py

**Comment by catlair** [comment]
> > 没明白过什么是青龙
> > 只看如何安装，没看到使用文档
> 
> 就是一个面板，能定时运行一些任务脚本，比如js、py

问题是没有案例我不知道如何准备好这些 js，没有文档不想去研究怎么弄，这对我毫无用处。 
直接 ql repo 它会导入全部 js 文件，并改名为 用户名_仓库名_文件名 。如果没有解决办法，意味着我需要重新整合代码。  
github 有 jd 的脚本案例，它们几乎每个文件就是单独的脚本，而我这个这个项目就是一个整体。  
我尝试过整合代码，如下
![image](https://user-images.githubusercontent.com/44313800/141444817-031c045f-b8c8-4426-a664-358131527fbb.png)

**Comment by lsdlh** [comment]
> > > 没明白过什么是青龙
> > > 只看如何安装，没看到使用文档
> > 
> > 
> > 就是一个面板，能定时运行一些任务脚本，比如js、py
> 
> 问题是没有案例我不知道如何准备好这些 js，没有文档不想去研究怎么弄，这对我毫无用处。 直接 ql repo 它会导入全部 js 文件，并改名为 用户名_仓库名_文件名 。如果没有解决办法，意味着我需要重新整合代码。 github 有 jd 的脚本案例，它们几乎每个文件就是单独的脚本，而我这个这个项目就是一个整体。 我尝试过整合代码，如下 ![image](https://user-images.githubusercontent.com/44313800/141444817-031c045f-b8c8-4426-a664-358131527fbb.png)

太麻烦就不用支持了，我用的docker版本

**Comment by catlair** [comment]
我仿佛想到了

**Comment by catlair** [comment]
已经算是简单的支持了

只需要这一个文件 https://github.com/catlair/BiliTools/tree/main/qinglong

![image](https://user-images.githubusercontent.com/44313800/141472699-79e4d842-d32e-4d96-bb55-7fd316cd78f8.png)

![image](https://user-images.githubusercontent.com/44313800/141472756-3a4254f4-3f63-4733-bf94-ff887d6cb8c9.png)

**Comment by melodyjerry** [comment]
@catlair  依赖也安装了，但是运行后是这样的，作者看看我这个是怎么回事
```
开始执行脚本
## 开始执行... 2021-12-22 19:41:37


node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'qs'
Require stack:
- /ql/scripts/catlair_BiliTools/ql_index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/catlair_BiliTools/ql_index.js:1:76)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/catlair_BiliTools/ql_index.js' ]
}


## 执行结束... 2021-12-22 19:41:37 耗时 0 秒
```

**Comment by catlair** [comment]
@melodyjerry 

这个没问题
![image](https://user-images.githubusercontent.com/44313800/147091000-ac8c041e-847b-4249-8e48-a66ae79c9eb4.png)

但是有另一个问题需要更新下
![image](https://user-images.githubusercontent.com/44313800/147091031-0e1a7d66-e1a8-4cac-9214-85f2bf63c615.png)

**Comment by melodyjerry** [comment]
> @melodyjerry
> 
> 这个没问题 ![image](https://user-images.githubusercontent.com/44313800/147091000-ac8c041e-847b-4249-8e48-a66ae79c9eb4.png)
> 
> 但是有另一个问题需要更新下 ![image](https://user-images.githubusercontent.com/44313800/147091031-0e1a7d66-e1a8-4cac-9214-85f2bf63c615.png)

请问我需要更新什么

**Comment by catlair** [comment]
@melodyjerry

https://raw.githubusercontent.com/catlair/BiliTools/main/qinglong/ql_index.js

这个代码替换之前的(青龙面板怎么用我也不知)
