### ISSUE TITLE
腾讯云函数多用户

### ISSUE THREAD

**Issue by greenfriend22** [catlair/BiliTools#45]
安照example 改的 报错了

Result:{"errorCode":-1,"errorMessage":"Error: 配置文件不存在或不正确！！！\n at setConfig (/var/user/config/setConfig.js:59:9)\n at Object.\u003canonymous\u003e (/var/user/config/setConfig.js:62:20)\n at Module._compile (internal/modules/cjs/loader.js:1158:30)\n at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)\n at Module.load (internal/modules/cjs/loader.js:1002:32)\n at Function.Module._load (internal/modules/cjs/loader.js:901:14)\n at Module.require (internal/modules/cjs/loader.js:1044:19)\n at require (internal/modules/cjs/helpers.js:77:18)\n at Object.\u003canonymous\u003e (/var/user/utils/cookie.js:12:18)\n

**Comment by KudouRan** [comment]
> tmd的 网卡了，页面没加载 css ，我把内容整到编辑上去了，艹


[scf 并不能支持多账号](https://github.com/catlair/BiliTools/blob/main/docs/%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2%E5%88%B0SCF.md#3-%E6%96%B0%E5%BB%BA%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%B9%B6%E6%B5%8B%E8%AF%95%E6%98%AF%E5%90%A6%E5%8F%AF%E7%94%A8)

由于 scf 可以拥有多个函数，所以并没有 scf 运行多个用户的方式。
提供的多用户方式是用于批量部署 scf 的。最终的变量还是被拆分成单个用户配置。

不知道你是看的哪部分文档，我好修改错误
