### ISSUE TITLE
青龙多账号问题

### ISSUE THREAD

**Issue by lsdlh** [catlair/BiliTools#46]
不支持多账号吗，单账号生成的配置文件没问题
![image](https://user-images.githubusercontent.com/45959509/144852136-b8ff1cd9-c078-44c0-bd72-9923e75cf80f.png)

**Comment by KudouRan** [comment]
现在已经支持多账号了，并且对之前做了调整。

- 文件名由 `ql_index.js` 换成 `cat_bili_ql.js`
- 配置文件名由 `config.json` 换成 `cat_bili_config.json`

**使用方式**
由于不熟悉，建议直接看青龙面板教程 <https://github.com/whyour/qinglong>

```bash
## 举例
ql raw https://raw.githubusercontent.com/catlair/BiliTools/main/qinglong/cat_bili_ql.js
```

创建一个配置文件
`cat_bili_config.json` 配置与其他相同

![图片](https://user-images.githubusercontent.com/81743795/148545405-3c9db19d-c3c9-46d2-b600-7bad0667337a.png)

或者使用环境变量（不推荐，因为别的程序也可以访问）

![图片](https://user-images.githubusercontent.com/81743795/148545529-73c95e3d-219f-4bf9-b266-7ad03bd9e9be.png)

**多账号的使用**

设置多个任务即可运行多帐号，这样做主要是把不同号的运行时间错开（不会有人几十个号还用这吧）

![图片](https://user-images.githubusercontent.com/81743795/148544689-dc8914cc-1634-4c94-8c4a-e17ed5e18707.png)

- `--item=3` 这是必须的，其中 3 表示运行配置中第 3 个，下标从 1 开始。设置错误或不设置则默认为 1 。
- 如果你想要直接运行测试一下，这个下标只会是 1。青龙面板的问题，它会 `--item` 错位，这是由于 api 强行添加了 now 命令。但是通过任务定时就不会出错。

**Comment by vc5** [comment]
建议：通过环境变量，指定配置文件位置

**Comment by QiHsMing** [comment]
[青龙面板挂B站任务问题.md](https://github.com/catlair/BiliTools/files/7874576/B.md)

**Comment by catlair** [comment]
@QiHsMing 抱歉，是我在提示上的疏忽，你这个错误原因是json不符合要求

```json
  "function": {
        "silver2Coin": true,
        "addCoins": true
        "liveSignTask": true,
```
其中 `"addCoins": true` 少了一个逗号
