### ISSUE TITLE
建议：通过环境变量，指定配置文件位置

### ISSUE THREAD

**Issue by KudouRan** [catlair/BiliTools#48]
建议：通过环境变量，指定配置文件位置

_Originally posted by @vc5 in https://github.com/catlair/BiliTools/issues/46#issuecomment-1009761678_

**Comment by KudouRan** [comment]
@vc5 你是指把 `cat_bili_config` 这个名字放到环境变量，还是把整个路径放环境变量。
后者的话把这个使用整复杂了，前者是因为这名字有问题吗🤔，只是为了避免和其他冲突。

**Comment by vc5** [comment]
避免命名冲突，给用户一个自定义配置文件名的选项
