### ISSUE TITLE
投币功能有问题

### ISSUE THREAD

**Issue by ZJGtale** [catlair/BiliTools#63]
【每日任务完成情况】----
[info 00:19:15] 投币获取经验: 0，还需投币数量: 5颗;(目标5颗)
[info 00:19:15] 每日分享: [未完成]
[info 00:19:15] 每日播放: [未完成]
[info 00:19:23] ----【直播签到】----
[info 00:19:23] 已签到，跳过签到
[info 00:19:23] 已经签到2天，再签到3天可以获得666银瓜子
[info 00:19:32] ----【分享/播放视频】----
[info 00:19:39] 获取视频: 【FATE相关】CRUCIS FATAL FAKE MV 《Faker》 --up【bishi】
[info 00:19:48] 分享视频成功!
[info 00:19:57] 播放视频成功!
[info 00:20:06] ----【视频投币】----
[warn 00:20:27] 给up投币失败 34005 超过投币上限啦~
[warn 00:20:38] 给up投币失败 34005 超过投币上限啦~

都是失败。

**Comment by catlair** [comment]
你是不是填写了自定义目标，而且目标大部分视频都已经被投了币。

**Comment by KudouRan** [comment]
现在 ‘超过投币上限啦’ 超过三次不会结束投币，而是去找特别关注、关注、全站热点。依次类推

**Comment by ZJGtale** [comment]
> 你是不是填写了自定义目标，而且目标大部分视频都已经被投了币。
> 
> 

不好意思，没看清楚参数配置，用的默认的id 0.

**Comment by catlair** [comment]
> > 你是不是填写了自定义目标，而且目标大部分视频都已经被投了币。
> 
> 不好意思，没看清楚参数配置，用的默认的id 0.

哦哦，会吧无效的id过滤掉的，现在修改了逻辑，不会有这种错误了
