### ISSUE TITLE
TypeError: 配置文件存在，但是无法解析！可能 JSON5 格式不正确！

### ISSUE THREAD

**Issue by timelast** [catlair/BiliTools#71]
![image](https://user-images.githubusercontent.com/92976221/170506917-e2fc2a0e-4450-4826-91ea-b7fb8ea2fbcb.png)

**Comment by timelast** [comment]
青龙面板中提示
以下两种配置均尝试过，但都不可以。
![image](https://user-images.githubusercontent.com/92976221/170507054-18273b31-701c-475f-808b-383e102a17ef.png)
![image](https://user-images.githubusercontent.com/92976221/170507172-bf73321f-b9ee-43ad-8f2b-3b89eca90918.png)

**Comment by timelast** [comment]
json格式已经在https://www.lddgo.net/string/json5校验过

**Comment by catlair** [comment]
自闭，确实存在这个问题，但本地却没有成功复现

**Comment by catlair** [comment]
暂时可以在青龙面板中安装
```bash
npm install -g @catlair/bilitools
```

然后把代码改成这样

```javascript
require('@catlair/bilitools').run()
```

![image](https://user-images.githubusercontent.com/44313800/170513391-139e85c9-20c7-4a53-815d-61c7da23d039.png)

**Comment by catlair** [comment]
青龙面板可能只支持上面这种方式了，他里面安装依赖的方式（pnpm）会导致 json5 这个包失效。

**Comment by catlair** [comment]
不需要变化了啊

版本是 v0.4.12-beta.1 吗

bilitools -v 可以看版本

![image](https://user-images.githubusercontent.com/44313800/170521377-e8bd6385-a2a7-4c61-bdbb-737f8ed29e1c.png)
