### ISSUE TITLE
[新增]: 更细致的天选时刻设置

### ISSUE THREAD

**Issue by gitiray** [catlair/BiliTools#75]
### 是否已经阅读文档

- [x] 我确定阅读过文档

### 1. 参与对象限制

希望可以设置只扫描已经关注的主播，否则扫描分区列表

### 2. 参与条件限制

天选时刻分为关注、粉丝牌、等级、无条件等，希望可以选定条件类型

**Comment by catlair** [comment]
已关注的恰好有天选挺难的吧。
关注、粉丝牌、等级、无条件，大多数都是关注，不明白这个设置项有啥意义(粉丝牌，舰长忽略不计，脚本不可能用钱去抽的)

**Comment by gitiray** [comment]
> 已关注的恰好有天选挺难的吧

这个应该是另一套逻辑，扫描已关注的、正在开播的直播间，再判断是否存在天选时刻。

主要是现有模式从分区列表扫描，很容易自动关注大量陌生人、自动取关，造成反复多条关注问候（领奖时挺尴尬），所以干脆不抽奖。但对于长期关注的直播间又希望能参与抽奖。

或者通过白名单指定直播间的方式，只扫描这些直播间的天选。

> 关注、粉丝牌、等级、无条件，大多数都是关注，不明白这个设置项有啥意义(粉丝牌，舰长忽略不计，脚本不可能用钱去抽的)

看了下代码限制是 `data.gift_price > 0`，应该不影响已有粉丝牌、舰长的情况，那么确实没有太大意义。

只是看到别的项目有这个区分，没有仔细考虑。

**Comment by KudouRan** [comment]
- [ ] 扫描已关注的用户
- [ ] 可选是否屏蔽需要关注

**Comment by gitiray** [comment]
测试可用，达到所需效果，感谢！
