### ISSUE TITLE
telegram推送失败

### ISSUE THREAD

**Issue by straint** [catlair/BiliTools#76]
## 开始执行... 2022-06-06 01:26:02

[info 01:26:03] 当前版本【v0.5.0】
[info 01:26:03] 可更新：最新版本【v0.5.0】
[info 01:26:03] ----【登录】----
[info 01:26:14] 登录成功: qwer
[info 01:26:14] 硬币余额: 78
[info 01:26:14] 当前等级: 3
[info 01:26:14] 距离升级还需要 850 经验，预计 13.00 天
[info 01:26:14] 大会员状态: 无大会员
[info 01:26:14] ----【每日任务完成情况】----
[info 01:26:24] 今日投币获取经验: 0，还需投币0颗，硬币不够了，不投币了
[info 01:26:24] 每日分享: 已完成
[info 01:26:24] 每日播放: 已完成
[info 01:26:32] ----【直播签到】----
[info 01:26:32] 已签到，跳过签到
[info 01:26:32] 已经签到1天，再签到4天可以获得666银瓜子
[info 01:26:41] ----【分享/播放视频】----
[info 01:26:41] 已完成，跳过分享/播放
[info 01:26:46] ----【银瓜子兑换硬币】----
[info 01:26:46] 兑换失败，你瓜子不够了
[info 01:26:50] ----【消息推送】----
[info 01:26:52] telegram发送通知消息失败！！
[info 01:26:52] HTTPError: Response code 400 (Bad Request)

## 执行结束... 2022-06-06 01:26:52 耗时 50 秒

**Comment by straint** [comment]
脚本运行在青龙面板，面板里其他脚本如jd可以正常推送

**Comment by KudouRan** [comment]
感谢反馈，已经修复，会在后续版本添加
